name: template proyect

on:
  push:
    branches: [ main ]

jobs:
  hello-word:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: list files
        run: ls -a
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm